import { expect, test } from '@playwright/test'
import { seedMockState, readCase } from '../helpers/seed'
const NO = 'WP-2569-000501'
for (const channel of ['direct', 'post']) {
  test(`หนังสือประสาน A4 นำส่ง ${channel} แล้วแนบหนังสือตอบรับก่อนคุ้มครอง`, async ({ page }) => {
    await seedMockState(page, 'Approved - วิธีที่ 4', undefined, {
      kb11Signed: true, stage: 'method_operation', approvedMethods: [4], orderedMethods: [4],
      dispatchedAt: '08/10/2569 01:00', deliveredAt: '2026-10-08T00:00:00Z', deliveryRecipient: 'สมชาย ใจดี', deliveryAckType: 'ใบตอบรับไปรษณีย์ (EMS)',
      consents: [{ ref: 'kb11', consented: true, by: 'สมชาย ใจดี' }], methodTracks: [{ method: 4, status: 'pending' }], officialLetters: [],
    })
    await page.goto('/protection-methods')
    await page.getByRole('link', { name: 'เปิดงาน', exact: true }).click()
    await expect(page.getByText('ช่องทางส่งหนังสือไม่ใช่การส่งมอบพยาน', { exact: false })).toHaveCount(0)
    await expect(page.getByText('คำร้องหลักต้องมี คบ.9 และ คบ.11', { exact: false })).toHaveCount(0)
    await expect(page.getByRole('heading', { name: 'หนังสือประสานขาออก', exact: true })).toHaveCount(0)
    const workspace = page.getByTestId('automatic-method4-workspace')
    await workspace.getByTestId('coordination-province').selectOption('นนทบุรี')
    const station = workspace.getByTestId('coordination-agency')
    const id = await station.locator('option', { hasText: 'สภ.ปากเกร็ด' }).getAttribute('value')
    await station.selectOption(id!)
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await workspace.getByRole('button', { name: 'ทำหนังสือประสาน', exact: true }).click()
    await page.getByTestId('coordination-letter-number').fill('ปป 004/2569')
    await page.getByRole('textbox', { name: 'เนื้อหาหนังสือประสาน', exact: true }).fill('ขอความร่วมมือคุ้มครองพยาน สมชาย ใจดี และแจ้งผลตอบรับเป็นหนังสือ')
    await expect(page.getByTestId('coordination-letter-preview')).toContainText('สถานีตำรวจภูธรปากเกร็ด')
    const download = page.waitForEvent('download')
    await page.getByRole('button', { name: 'ดาวน์โหลดหนังสือสำหรับพิมพ์ A4' }).click()
    expect((await download).suggestedFilename()).toContain(NO)
    await page.reload()
    await workspace.getByRole('button', { name: 'ทำหนังสือประสาน', exact: true }).click()
    await expect(page.getByTestId('coordination-letter-preview')).toContainText('ขอความร่วมมือคุ้มครองพยาน สมชาย ใจดี')
    await page.getByLabel('ส่งหนังสือประสานโดย', { exact: true }).selectOption(channel)
    if (channel === 'post') await page.getByRole('textbox', { name: 'เลขติดตามไปรษณีย์', exact: true }).fill('EMS-001')
    await page.getByTestId('coordination-send-outgoing').click()
    await page.locator('.swal2-cancel').click()
    expect((await readCase(page, NO))?.officialLetters).toEqual([])
    await page.getByTestId('coordination-send-outgoing').click()
    await page.locator('.swal2-confirm').click()
    await expect(workspace.getByRole('heading', { name: 'หนังสือตอบกลับขาเข้า', exact: true })).toBeVisible()
    const sent = ((await readCase(page, NO))?.officialLetters as any[])[0]
    expect(sent.channel).toBe(channel)
    expect(sent.draftSnapshot.body).toContain('สมชาย ใจดี')
    expect(sent.agency).toBe('สถานีตำรวจภูธรปากเกร็ด')
    await workspace.getByTestId('coordination-accept').click()
    await expect(page.locator('.swal2-popup:not(.swal2-toast)')).toHaveCount(0)
    await expect(page.getByTestId('protection-duration')).toHaveCount(0)
    await page.evaluate(async () => {
      const path = '/scripts/post-approval-fixture.ts'
      const { useCaseStore } = await import(path)
      useCaseStore.getState().setMethodStatus('WP-2569-000501', 4, 'active')
    })
    expect(((await readCase(page, NO))?.methodTracks as any[])[0].status).toBe('preparing')
    await workspace.getByTestId('coordination-incoming-file-input').setInputFiles({ name: 'หนังสือตอบรับ.pdf', mimeType: 'application/pdf', buffer: Buffer.from('test response evidence') })
    await expect(workspace.getByRole('link', { name: 'หนังสือตอบรับ.pdf', exact: true })).toBeVisible()
    await workspace.getByTestId('coordination-accept').click()
    await page.locator('.swal2-cancel').click()
    expect(((await readCase(page, NO))?.methodTracks as any[])[0].coordination.responseStatus).toBe('awaiting')
    await workspace.getByTestId('coordination-accept').click()
    await page.locator('.swal2-confirm').click()
    await expect(page).toHaveURL(/\/protection-duration\?caseNo=WP-2569-000501/)
    await expect(page.getByTestId('protection-time-bar')).toContainText('30 วัน')
    await page.reload()
    const reply = ((await readCase(page, NO))?.officialLetters as any[]).find((l) => l.direction === 'incoming')
    expect(reply.documentName).toBe('หนังสือตอบรับ.pdf')
    expect(reply.documentPreviewUrl).toMatch(/^data:application\/pdf;base64,/)
    await expect(page).toHaveURL(/\/protection-duration\?caseNo=WP-2569-000501/)
    await expect(page.getByTestId('protection-time-bar')).toContainText('30 วัน')
    await page.goto('/protection-methods')
    await page.getByRole('link', { name: 'เปิดงาน', exact: true }).click()
    await expect(page.getByTestId('coordination-summary')).toContainText('สถานีตำรวจภูธรปากเกร็ด')
    await expect(page.getByRole('link', { name: 'หนังสือตอบรับ.pdf', exact: true })).toBeVisible()
    await expect(page.getByTestId('protection-duration')).toHaveCount(0)
    await page.getByRole('link', { name: 'ไปภาพรวมการคุ้มครอง', exact: true }).click()
    await expect(page.getByRole('tablist')).toHaveCount(0)
    await expect(page.getByTestId('protection-time-bar')).toHaveCount(0)
    await page.getByRole('link', { name: 'ดูระยะเวลาคุ้มครอง', exact: true }).click()
    await expect(page).toHaveURL(/\/protection-duration\?caseNo=WP-2569-000501/)
    await expect(page.getByTestId('protection-time-bar')).toBeVisible()
    await expect(page.getByText('ข้อมูลการประสานและเตรียมส่งมอบ', { exact: true })).toHaveCount(0)
    await expect(page.getByTestId('protection-time-bar')).not.toContainText('รอบันทึกวันเริ่มจริง')
    await page.getByRole('button', { name: 'เพิ่มหนังสือ คบ.13', exact: true }).click()
    await page.getByLabel('รอบเดือนรายงาน').fill('2026-11')
    await page.getByLabel('อัปโหลดหนังสือ คบ.13').setInputFiles({ name: 'คบ13-พฤศจิกายน.pdf', mimeType: 'application/pdf', buffer: Buffer.from('report evidence') })
    await expect(page.getByRole('dialog', { name: 'เพิ่มหนังสือ คบ.13', exact: true })).not.toBeVisible()
    await page.reload()
    await expect(page.getByRole('link', { name: 'คบ13-พฤศจิกายน.pdf', exact: true })).toBeVisible()
    expect((await readCase(page, NO))?.protectionReportUploads).toHaveLength(1)
    expect((await readCase(page, NO))?.actualStartedAt).toBeFalsy()
    await expect(page.getByRole('link', { name: 'ยุติคุ้มครองพยาน', exact: true })).toHaveAttribute('href', '/termination/WP-2569-000501')
  })
}
