import { expect, test, type Page } from '@playwright/test'
import { readCase, seedMockState } from '../helpers/seed'
import { handoffAction } from '../helpers/postApproval'
import { choosePreliminaryOutcome, confirmInlineDecision, decisionWorkspace, fillDecisionWorkspace, notificationCount, saveDecisionWorkspace } from '../helpers/noticeDecisionWorkspace'

const NO = 'WP-2569-000501'
const DOSSIER = `/dossier/${NO}`
const role = (page: Page, value: string) => page.getByLabel('เลือกบทบาทผู้ใช้งาน').selectOption(value)
const noFinalEffects = async (page: Page, before: Record<string, any> | null, notifications: number) => {
  const after = await readCase(page, NO)
  expect(after?.activity7State).toBe(before?.activity7State)
  expect(after?.kb9Signed).toBe(before?.kb9Signed)
  expect(after?.kb10Signed).toBe(before?.kb10Signed)
  expect(after?.secretarySignedAt).toBe(before?.secretarySignedAt)
  expect(after?.protectionHandoff).toEqual(before?.protectionHandoff)
  expect(after?.documents).toEqual(before?.documents)
  expect(after?.dispatchedAt).toBe(before?.dispatchedAt)
  expect(await notificationCount(page)).toBe(notifications)
}
const assertFormCount = async (page: Page) => {
  const c = await readCase(page, NO)
  const formNo = (c?.preliminaryDecision as any)?.formNo
  await page.getByTestId('notice-decision-back').click()
  const count = await page.getByTestId('dossier-form-row').count()
  await expect(page.getByTestId('dossier-form-count')).toContainText(`(${count} แบบ)`)
  const row = page.locator(`[data-testid="dossier-form-row"][data-form-number="${formNo}"]`)
  await expect(row).toHaveCount(1)
  await row.getByRole('button', { name: 'เปิดแบบฟอร์ม', exact: true }).click()
  await expect(decisionWorkspace(page)).toBeVisible()
}

for (const formNo of [9, 10] as const) {
  test(`กดครั้งแรกเปิด คบ.${formNo} ในหน้าแบบฟอร์มแยก บันทึก/กลับ/รีเฟรชโดยไม่ลงนามหรือส่งงาน`, async ({ page }) => {
    await seedMockState(page, 'PostApproval 1')
    await page.goto(DOSSIER)
    const before = await readCase(page, NO)
    const notifications = await notificationCount(page)
    await choosePreliminaryOutcome(page, formNo)
    await assertFormCount(page)
    await expect(page.getByTestId('notice-decision-status')).toContainText('ร่าง')
    await expect(page.getByTestId('notice-decision-case-no')).toContainText(NO)
    expect(await page.getByTestId('notice-decision-case-no').getByRole('textbox').count()).toBe(0)
    await noFinalEffects(page, before, notifications)
    await fillDecisionWorkspace(page)
    await page.getByTestId('notice-decision-detail-เลขที่หนังสือ').fill('ปป 001')
    await saveDecisionWorkspace(page)
    await noFinalEffects(page, before, notifications)
    await page.reload()
    await expect(decisionWorkspace(page)).toBeVisible()
    await expect(page.getByTestId('notice-decision-reason')).toHaveValue('ผลพิจารณาจากข้อเท็จจริงสมมติ')
    await expect(page.getByTestId('notice-decision-detail-เลขที่หนังสือ')).toHaveValue('ปป 001')
    await page.getByTestId('notice-decision-back').click()
    await expect(decisionWorkspace(page)).toHaveCount(0)
    await choosePreliminaryOutcome(page, formNo)
    await expect(page.getByTestId('notice-decision-reason')).toHaveValue('ผลพิจารณาจากข้อเท็จจริงสมมติ')
    await assertFormCount(page)
    await noFinalEffects(page, before, notifications)
  })
}

test('เปลี่ยนผลก่อนยืนยันเก็บร่างอีกแบบและเปิดฉบับตรงกับผลล่าสุด', async ({ page }) => {
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  const before = await readCase(page, NO)
  const notifications = await notificationCount(page)
  await choosePreliminaryOutcome(page, 9)
  await fillDecisionWorkspace(page, 'got')
  await page.getByTestId('notice-decision-reason').fill('เหตุผลอนุมัติฉบับ A')
  await page.getByTestId('notice-decision-detail-เลขที่หนังสือ').fill('ปป A')
  await saveDecisionWorkspace(page)
  await page.getByTestId('notice-decision-back').click()
  await choosePreliminaryOutcome(page, 10)
  await expect(decisionWorkspace(page)).toContainText('คบ.10')
  await fillDecisionWorkspace(page)
  await page.getByTestId('notice-decision-reason').fill('เหตุผลไม่อนุมัติฉบับ B')
  await page.getByTestId('notice-decision-detail-เลขที่หนังสือ').fill('ปป B')
  await saveDecisionWorkspace(page)
  await page.getByTestId('notice-decision-back').click()
  await choosePreliminaryOutcome(page, 9)
  await expect(decisionWorkspace(page)).toContainText('คบ.9')
  await expect(page.getByTestId('notice-decision-reason')).toHaveValue('เหตุผลอนุมัติฉบับ A')
  await expect(page.getByTestId('notice-decision-detail-เลขที่หนังสือ')).toHaveValue('ปป A')
  const c = await readCase(page, NO)
  expect((c?.noticeDecisionDrafts as any)?.[10].reason).toBe('เหตุผลไม่อนุมัติฉบับ B')
  expect((c?.preliminaryDecision as any)?.formNo).toBe(9)
  await assertFormCount(page)
  await noFinalEffects(page, before, notifications)
})

test('หน้าแบบฟอร์มโดยตรงย้อนกลับไปเลือกผลได้ แล้วเปิดร่างเดิมพร้อมข้อมูล', async ({ page }) => {
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  await choosePreliminaryOutcome(page, 9)
  await fillDecisionWorkspace(page)
  await page.getByTestId('notice-decision-reason').fill('ร่างที่เปิดจากหน้าแบบฟอร์ม')
  await saveDecisionWorkspace(page)
  await page.goto(`/form/9?caseNo=${NO}`)
  await expect(decisionWorkspace(page)).toBeVisible()
  await expect(page.getByTestId('notice-decision-reason')).toHaveValue('ร่างที่เปิดจากหน้าแบบฟอร์ม')
  await page.getByTestId('notice-decision-back').click()
  await expect(page).toHaveURL(new RegExp(`/dossier/${NO}`))
  await expect(decisionWorkspace(page)).toHaveCount(0)
  await expect(page.getByTestId('approve-case-button')).toBeVisible()
  await expect(page.getByTestId('reject-case-button')).toBeVisible()
  await choosePreliminaryOutcome(page, 9)
  await expect(page.getByTestId('notice-decision-reason')).toHaveValue('ร่างที่เปิดจากหน้าแบบฟอร์ม')
  await page.reload()
  await expect(decisionWorkspace(page)).toBeVisible()
})

test('ข้อมูลที่ยังไม่บันทึกเตือนก่อนย้อนกลับหรือรีเฟรช ยกเลิกแล้วคงข้อมูลเดิม', async ({ page }) => {
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  const before = await readCase(page, NO)
  const notifications = await notificationCount(page)
  await choosePreliminaryOutcome(page, 9)
  await page.getByTestId('notice-decision-reason').fill('ข้อความที่ยังไม่บันทึก')
  let backWarning = ''
  page.once('dialog', async (dialog) => { backWarning = dialog.message(); await dialog.dismiss() })
  await page.getByTestId('notice-decision-back').click()
  expect(backWarning).toContain('ยังไม่บันทึก')
  await expect(decisionWorkspace(page)).toBeVisible()
  await expect(page.getByTestId('notice-decision-reason')).toHaveValue('ข้อความที่ยังไม่บันทึก')
  let reloadWarning = ''
  page.once('dialog', async (dialog) => { reloadWarning = dialog.type(); await dialog.dismiss() })
  // ยกเลิก beforeunload แล้วไม่มี navigation ให้รอจน load; อย่าให้กินเวลาเทสต์ทั้งหมด
  await page.reload({ timeout: 3000 }).catch(() => undefined)
  expect(reloadWarning).toBe('beforeunload')
  await expect(page.getByTestId('notice-decision-reason')).toHaveValue('ข้อความที่ยังไม่บันทึก')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByTestId('notice-decision-back').click()
  await expect(decisionWorkspace(page)).toHaveCount(0)
  await choosePreliminaryOutcome(page, 10)
  await expect(decisionWorkspace(page)).toContainText('คบ.10')
  await noFinalEffects(page, before, notifications)
})

for (const destination of ['original_owner', 'got'] as const) {
  test(`ยืนยันจากพื้นที่แบบฟอร์มลงนามครั้งเดียวและส่งงาน ${destination} หลังยืนยันจริง`, async ({ page }) => {
    await seedMockState(page, 'PostApproval 1')
    await page.goto(DOSSIER)
    await choosePreliminaryOutcome(page, 9)
    await fillDecisionWorkspace(page, destination)
    await confirmInlineDecision(page)
    await expect.poll(async () => (await readCase(page, NO))?.activity7State).toBe('approved')
    const signed = await readCase(page, NO)
    expect((signed?.protectionHandoff as any)?.destination).toBe(destination)
    expect((signed?.resultNotices as any)?.[9]?.status).toBe('signed_incomplete')
    expect((signed?.resultNotices as any)?.[10]?.original).toBeUndefined()
    await expect(page.getByTestId('notice-decision-confirm')).toHaveCount(0)
    await expect(page.getByTestId('reject-case-button')).toHaveCount(0)
    const duplicate = await page.evaluate(async () => {
      const path = '/scripts/post-approval-fixture.ts'
      const { useCaseStore } = await import(path)
      return useCaseStore.getState().confirmPreliminaryDecision('WP-2569-000501', 9)
    })
    expect(duplicate).toBe(false)
    expect((await readCase(page, NO))?.documents).toEqual(signed?.documents)
    if (destination === 'got') {
      await role(page, 'got_receiver')
      await handoffAction(page, 'receive')
      await handoffAction(page, 'submit')
      await role(page, 'got_director')
      await page.getByTestId('got-assignee-select').selectOption('GOT-OFF-001')
      await handoffAction(page, 'assign', 'มอบหมายตามผลพิจารณาเดิม')
      await role(page, 'got_officer')
      await handoffAction(page, 'accept')
      expect((await readCase(page, NO))?.assignedOfficerUserId).toBe('OFF-001')
    }
    await page.reload()
    expect((await readCase(page, NO))?.kb9SignedAt).toBe(signed?.kb9SignedAt)
  })
}

test('ยืนยันไม่อนุมัติจากแบบฟอร์มลงนาม คบ.10 โดยไม่สร้างเส้น กอท.', async ({ page }) => {
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  await choosePreliminaryOutcome(page, 10)
  await fillDecisionWorkspace(page)
  await expect(page.getByTestId('notice-decision-destination')).toHaveCount(0)
  await confirmInlineDecision(page)
  await expect.poll(async () => (await readCase(page, NO))?.activity7State).toBe('rejected')
  const c = await readCase(page, NO)
  expect(c?.kb10Signed).toBe(true)
  expect(c?.kb9Signed).not.toBe(true)
  expect(c?.protectionHandoff).toBeUndefined()
  expect((c?.resultNotices as any)?.[10]?.status).toBe('signed_incomplete')
  expect(c?.dispatchedAt).toBeUndefined()
})

test('ยืนยันล้มเหลวยังคงข้อมูล ไม่มีผลสำเร็จ และลองใหม่ได้', async ({ page }) => {
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  const before = await readCase(page, NO)
  const notifications = await notificationCount(page)
  await choosePreliminaryOutcome(page, 9)
  await fillDecisionWorkspace(page)
  await page.getByTestId('notice-decision-detail-เลขที่หนังสือ').fill('ปป RETRY')
  await page.evaluate(async () => {
    const path = '/scripts/post-approval-fixture.ts'
    const { useCaseStore } = await import(path)
    ;(window as any).__noticeWorkspaceConfirm = useCaseStore.getState().confirmPreliminaryDecision
    useCaseStore.setState({ confirmPreliminaryDecision: () => false })
  })
  await confirmInlineDecision(page, false)
  await expect(page.getByTestId('notice-decision-error')).toBeVisible()
  await expect(page.getByTestId('notice-decision-reason')).toHaveValue('ผลพิจารณาจากข้อเท็จจริงสมมติ')
  await expect(page.getByTestId('notice-decision-detail-เลขที่หนังสือ')).toHaveValue('ปป RETRY')
  await noFinalEffects(page, before, notifications)
  await page.evaluate(async () => {
    const path = '/scripts/post-approval-fixture.ts'
    const { useCaseStore } = await import(path)
    useCaseStore.setState({ confirmPreliminaryDecision: (window as any).__noticeWorkspaceConfirm })
    delete (window as any).__noticeWorkspaceConfirm
  })
  await confirmInlineDecision(page)
  await expect.poll(async () => (await readCase(page, NO))?.activity7State).toBe('approved')
})

test('พื้นที่แบบฟอร์มใช้งานด้วยคีย์บอร์ดที่390/1440และซูม200%ปุ่มเข้าถึงได้', async ({ page }) => {
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  await choosePreliminaryOutcome(page, 9)
  await page.getByTestId('notice-decision-expand-preview').click()
  await expect(page.getByTestId('notice-decision-expand-preview')).toHaveAttribute('aria-expanded', 'true')
  await decisionWorkspace(page).getByRole('button', { name: 'หน้า 1', exact: true }).click()
  await expect(decisionWorkspace(page).getByRole('button', { name: 'หน้า 1', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.getByTestId('notice-decision-expand-preview').click()
  await expect(page.getByTestId('notice-decision-expand-preview')).toHaveAttribute('aria-expanded', 'false')
  for (const [width, zoom] of [[1440, '1'], [390, '1'], [1440, '2']] as const) {
    await page.setViewportSize({ width, height: 1000 })
    await page.evaluate((value) => { document.documentElement.style.zoom = value }, zoom)
    await page.getByTestId('notice-decision-number').focus()
    await page.keyboard.press('Tab')
    expect(await decisionWorkspace(page).evaluate((el) => el.contains(document.activeElement))).toBe(true)
    expect(await page.evaluate(() => document.activeElement?.matches(':focus-visible'))).toBe(true)
    const workspaceBox = await decisionWorkspace(page).boundingBox()
    expect(workspaceBox!.x).toBeGreaterThanOrEqual(-1)
    expect(workspaceBox!.x + workspaceBox!.width).toBeLessThanOrEqual(width + 1)
    await page.getByTestId('notice-decision-confirm').scrollIntoViewIfNeeded()
    await expect(page.getByTestId('notice-decision-confirm')).toBeVisible()
    const button = await page.getByTestId('notice-decision-confirm').boundingBox()
    expect(button!.x).toBeGreaterThanOrEqual(-1)
    expect(button!.x + button!.width).toBeLessThanOrEqual(width + 1)
    expect(button!.y).toBeGreaterThanOrEqual(-1)
    expect(button!.y + button!.height).toBeLessThanOrEqual(1001)
    await page.screenshot({ path: `/private/tmp/a6-notice-workspace-${width}-zoom${zoom}.png`, fullPage: true })
  }
})
