import { expect, test, type Page } from '@playwright/test'
import { readCase, seedMockState } from '../helpers/seed'
import { confirmSecretaryApproval, handoffAction } from '../helpers/postApproval'
import { checkNoticeReady, completeNoticeDetails, dispatchNotice } from '../helpers/noticeDocuments'

const NO = 'WP-2569-000501'
const DOSSIER = `/dossier/${NO}`
const role = (page: Page, value: string) => page.getByLabel('เลือกบทบาทผู้ใช้งาน').selectOption(value)
const readNotice = async (page: Page, formNo = 9) => ((await readCase(page, NO))?.resultNotices as Record<string, any>)?.[formNo]

for (const formNo of [9, 10]) {
  test(`คบ.${formNo} ลงนามตามผลเพียงครั้งเดียว → เติมรุ่นใหม่ → ตรวจพร้อมส่ง → เก็บฉบับส่ง`, async ({ page }) => {
    await seedMockState(page, 'PostApproval 1')
    await page.goto(DOSSIER)
    await page.getByTestId(formNo === 9 ? 'approve-case-button' : 'reject-case-button').click()
    await expect(page.getByTestId('decision-notice-preview')).toContainText(`คบ.${formNo}`)
    await expect(page.getByTestId('decision-notice-preview')).toContainText('อนุญาตเติมหลังลงนาม')
    if (formNo === 9) await confirmSecretaryApproval(page)
    else {
      await page.getByTestId('decision-reason-input').fill('ไม่เข้าหลักเกณฑ์การคุ้มครอง (ข้อมูลสมมติ)')
      await page.getByTestId('decision-confirm-button').click()
      await expect(page.getByTestId('decision-review-step')).toBeVisible()
      await page.getByTestId('decision-confirm-button').click()
    }
    await expect.poll(async () => Boolean((await readNotice(page, formNo))?.original)).toBe(true)
    const signed = await readNotice(page, formNo)
    const original = signed.original
    expect((await readNotice(page, formNo === 9 ? 10 : 9))?.original).toBeUndefined()
    expect(signed.status).toBe('signed_incomplete')
    const caseSigned = await readCase(page, NO)
    await role(page, 'officer')
    await expect(page.getByTestId('result-notice-status')).toContainText('รอเติมรายละเอียด')
    await expect(page.getByRole('button', { name: 'เสนอเลขาธิการฯ ลงนาม คบ.9' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: /บันทึกการนำส่ง$/ })).toHaveCount(0)
    await expect(page.getByTestId('notice-missing-fields')).toContainText('เลขที่หนังสือ')
    await completeNoticeDetails(page)
    let filled = await readNotice(page, formNo)
    expect(filled.original).toEqual(original)
    expect(filled.versions).toHaveLength(2)
    expect(filled.versions[1].signatureVerification).toBe('not_covered_by_original_signature')
    expect(filled.audit[0].changes.length).toBeGreaterThan(0)
    expect(filled.audit[0].userId).toBe('OFF-001')
    expect(filled.audit[0].at).toBeTruthy()
    expect((await readCase(page, NO))?.activity7State).toBe(caseSigned?.activity7State)
    expect((await readCase(page, NO))?.secretarySignedAt).toBe(caseSigned?.secretarySignedAt)
    await page.getByTestId('notice-audit-history').locator('summary').click()
    await expect(page.getByTestId('notice-audit-history')).toContainText('ปป 001')
    await page.reload()
    expect((await readNotice(page, formNo)).original).toEqual(original)
    expect((await readNotice(page, formNo)).versions).toHaveLength(2)
    await checkNoticeReady(page)
    await dispatchNotice(page)
    const sent = await readNotice(page, formNo)
    expect(sent.dispatches).toHaveLength(1)
    expect(sent.dispatches[0].snapshot).toEqual(sent.versions[1])
    expect(sent.dispatches[0].evidence.description).toContain('จำลอง')
    await page.reload()
    filled = await readNotice(page, formNo)
    expect(filled.status).toBe('sent')
    expect(filled.original).toEqual(original)
    await page.goto(`/form/${formNo}?caseNo=${NO}`)
    await expect(page.getByText(/มีการเติมรายละเอียดหลังลงนาม/).first()).toBeVisible()
    await expect(page.getByText(/ลายมือชื่อ.*จำลอง/).first()).toBeVisible()
    const inspector = page.getByTestId('notice-version-inspector')
    await page.getByTestId('notice-version-select').selectOption('1')
    await inspector.locator('summary').click()
    await expect(inspector).not.toContainText('ปป 001')
    await page.getByTestId('notice-version-select').selectOption('2')
    await expect(inspector).toContainText('ปป 001')
    await expect(inspector).toContainText('ลายมือชื่อเดิมไม่รับรองเนื้อหาที่เติมใหม่')
    await page.screenshot({ path: `/private/tmp/a6-notice-kb${formNo}-versions.png`, fullPage: true })
  })
}

test('GOT รับผ่านธุรการและ ผอ. ก่อนผู้ได้รับมอบหมายเติม เจ้าของเดิมและธุรการไม่มีสิทธิ', async ({ page }) => {
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  await page.getByTestId('approve-case-button').click()
  await confirmSecretaryApproval(page, 'got')
  const original = (await readNotice(page)).original
  await role(page, 'officer')
  await expect(page.getByTestId('notice-save-details')).toHaveCount(0)
  await role(page, 'got_receiver')
  await expect(page.getByTestId('notice-save-details')).toHaveCount(0)
  await expect(page.getByTestId('got-assignee-select')).toHaveCount(0)
  await handoffAction(page, 'receive')
  await handoffAction(page, 'submit')
  await role(page, 'got_director')
  await expect(page.getByTestId('notice-save-details')).toHaveCount(0)
  await page.getByTestId('got-assignee-select').selectOption('GOT-OFF-001')
  await handoffAction(page, 'assign', 'มอบหมายผู้รับผิดชอบตามคำสั่งเดิม')
  await role(page, 'got_officer')
  await expect(page.getByTestId('notice-save-details')).toHaveCount(0)
  await handoffAction(page, 'accept')
  await completeNoticeDetails(page)
  expect((await readNotice(page)).audit[0].userId).toBe('GOT-OFF-001')
  expect((await readNotice(page)).original).toEqual(original)
  expect((await readCase(page, NO))?.assignedOfficerUserId).toBe('OFF-001')
  await checkNoticeReady(page)
  await dispatchNotice(page)
  expect((await readNotice(page)).dispatches[0].by).toBe('นางสาวณิชา คุ้มภัย')
})

test('ข้อมูลยังขาดส่งไม่ได้ กดซ้ำไม่เพิ่มรุ่นหรือเอกสาร และ generic editor แก้ฉบับเดิมไม่ได้', async ({ page }) => {
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  await page.getByTestId('approve-case-button').click()
  await confirmSecretaryApproval(page)
  await role(page, 'officer')
  const original = (await readNotice(page)).original
  await page.getByTestId('notice-detail-เลขที่หนังสือ').fill('ปป 001')
  await page.getByTestId('notice-save-details').click()
  await expect(page.getByTestId('result-notice-status')).toContainText('รอเติมรายละเอียด')
  await expect(page.getByTestId('notice-check-ready')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /บันทึกการนำส่ง$/ })).toHaveCount(0)
  await page.getByTestId('notice-save-details').click()
  expect((await readNotice(page)).versions).toHaveLength(2)
  await page.goto(`/form/9?caseNo=${NO}`)
  const illegal = await page.evaluate(async () => {
    const path = '/scripts/post-approval-fixture.ts'
    const { useCaseStore, useFormDraftStore } = await import(path)
    useFormDraftStore.getState().updateSignedField(9, 'เลขาธิการ', 'เปลี่ยนผู้ลงนาม')
    useFormDraftStore.getState().updateField(9, 'วันที่อนุมัติ', 'เปลี่ยนวัน')
    useFormDraftStore.getState().reviseForm(9, 'ผิดสิทธิ', 'แก้ทับ')
    useCaseStore.getState().updateCase('WP-2569-000501', { activity7State: 'rejected', secretarySignedAt: 'เปลี่ยน' })
    return useCaseStore.getState().getCase('WP-2569-000501')?.resultNotices?.[9]?.original
  })
  expect(illegal).toEqual(original)
  await page.reload()
  expect((await readNotice(page)).original).toEqual(original)
  expect((await readCase(page, NO))?.activity7State).toBe('approved')
})
