import { expect, test, type Page } from '@playwright/test'
import { readCase, seedMockState } from '../helpers/seed'
import { confirmSecretaryApproval, handoffAction } from '../helpers/postApproval'
import { checkNoticeReady, completeNoticeDetails } from '../helpers/noticeDocuments'
import { confirmDialog, fieldAfterLabel, formRow, signInModal } from '../journeys/journey-helpers'

const NO = 'WP-2569-000501'
test.use({ actionTimeout: 10_000 })
const DOSSIER = `/dossier/${NO}`
const selectRole = async (page: Page, role: string) => page.getByLabel('เลือกบทบาทผู้ใช้งาน').selectOption(role)
const readHandoff = async (page: Page) => (await readCase(page, NO))?.protectionHandoff as Record<string, any> | undefined

test('เลือกปลายทางก่อนยืนยัน ตรวจสอบผู้รับ และส่งให้เจ้าของสำนวนเดิมโดยไม่เข้าคิว กอท.', async ({ page }) => {
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  await page.getByTestId('approve-case-button').click()
  await expect(page.getByTestId('decision-destination-select')).toHaveValue('')
  await page.getByTestId('decision-confirm-button').click()
  await expect(page.getByTestId('decision-validation-error')).toContainText('เลือกผู้รับผิดชอบ')
  expect((await readCase(page, NO))?.activity7State).not.toBe('approved')
  await page.getByTestId('decision-destination-select').selectOption('original_owner')
  await expect(page.getByTestId('decision-recipient')).toContainText('นางสาวอรุณี ใจมั่น')
  await page.getByTestId('decision-instruction-input').fill('ให้เจ้าของสำนวนเดิมดำเนินการคุ้มครองตามคำสั่ง')
  await page.getByTestId('decision-confirm-button').click()
  await expect(page.getByTestId('decision-review-step')).toContainText('30 วัน')
  await expect(page.getByTestId('decision-review-step')).toContainText('วิธีที่ 1')
  expect((await readCase(page, NO))?.activity7State).not.toBe('approved')
  await page.getByRole('button', { name: 'กลับไปแก้ไข' }).click()
  await expect(page.getByTestId('decision-destination-select')).toHaveValue('original_owner')
  await confirmSecretaryApproval(page)
  await selectRole(page, 'officer')
  await page.goto('/queue/officer')
  await expect(page.getByRole('row', { name: new RegExp(NO) })).toBeVisible()
  await page.goto('/notifications')
  await expect(page.getByText(/ส่งให้เจ้าของสำนวนเดิมดำเนินการต่อ/)).toBeVisible()
  await selectRole(page, 'got_receiver')
  await page.goto('/queue/got_receiver')
  await expect(page.getByRole('row', { name: new RegExp(NO) })).toHaveCount(0)
  await page.reload()
  expect((await readHandoff(page))?.destination).toBe('original_owner')
  expect((await readHandoff(page))?.events).toHaveLength(1)
})

test('กอท. ผ่านธุรการ → ผอ. → ผู้รับผิดชอบ และเดินโฟลว์เดิมจนเริ่มคุ้มครองได้', async ({ page }) => {
  test.setTimeout(150_000)
  await seedMockState(page, 'PostApproval 1')
  await page.goto(DOSSIER)
  await page.getByTestId('approve-case-button').click()
  await confirmSecretaryApproval(page, 'got', 'ให้ กอท. ดำเนินการตามผลอนุมัติและรายงานความก้าวหน้า')
  const approved = await readCase(page, NO)
  const orderNo = approved?.decisionNumber
  const originalOwner = approved?.assignedOfficerUserId
  const baseDocs = approved?.documents

  await selectRole(page, 'officer')
  await page.goto('/queue/officer')
  await expect(page.getByRole('row', { name: new RegExp(NO) })).toHaveCount(0)
  await page.goto(DOSSIER)
  await expect(page.getByRole('button', { name: 'เสนอเลขาธิการฯ ลงนาม คบ.9' })).toHaveCount(0)
  await page.goto('/protection-methods')
  await expect(page.getByText(NO, { exact: true })).toHaveCount(0)

  await selectRole(page, 'got_receiver')
  await page.goto('/queue/got_receiver')
  const row = page.getByRole('row', { name: new RegExp(NO) })
  await expect(row).toContainText('ผลพิจารณา: อนุมัติ')
  await row.getByRole('link', { name: 'เปิดแฟ้ม' }).click()
  const card = page.getByTestId('protection-handoff-card')
  await expect(card).toContainText('30 วัน')
  await expect(card).toContainText('คำสั่งอนุมัติคุ้มครองพยาน')
  await expect(page.getByTestId('got-assignee-select')).toHaveCount(0)
  await expect(page.getByTestId('got-submit-button')).toHaveCount(0)
  await handoffAction(page, 'receive', 'ตรวจเอกสารครบ รับเข้าคิว กอท.')
  await expect.poll(async () => (await readHandoff(page))?.step).toBe('received')
  await page.reload()
  await expect(page.getByTestId('got-submit-button')).toBeVisible()
  await handoffAction(page, 'submit', 'เสนอ ผอ. กอท. มอบหมายผู้รับผิดชอบ')
  await page.goto('/queue/got_receiver')
  await expect(page.getByRole('row', { name: new RegExp(NO) })).toHaveCount(0)

  await selectRole(page, 'got_director')
  await page.goto('/notifications')
  await expect(page.getByText(/ธุรการคดี กอท. ส่งเสนอ ผอ. กอท./)).toBeVisible()
  await page.goto('/queue/got_director')
  await page.getByRole('row', { name: new RegExp(NO) }).getByRole('link', { name: 'เปิดแฟ้ม' }).click()
  await page.getByTestId('got-assign-button').click()
  await expect(page.getByRole('alert')).toContainText('เลือกผู้รับผิดชอบ')
  await expect(page.getByTestId('got-assignee-select').locator('option')).toHaveCount(3)
  await page.getByTestId('got-assignee-select').selectOption('GOT-OFF-001')
  await handoffAction(page, 'assign', 'มอบหมาย นางสาวณิชา คุ้มภัย รับผิดชอบตามคำสั่งเดิม')
  await page.reload()
  await expect(page.getByTestId('handoff-status')).toContainText('รอผู้รับผิดชอบรับงาน')

  await selectRole(page, 'got_officer')
  await page.goto('/queue/got_officer')
  await page.getByRole('row', { name: new RegExp(NO) }).getByRole('link', { name: 'เปิดแฟ้ม' }).click()
  await expect(card).toContainText('ผลพิจารณา')
  await expect(card).toContainText('วิธีคุ้มครองที่อนุมัติ')
  await expect(card).toContainText('เจ้าของสำนวนเดิม (อ้างอิง)')
  await expect(page.getByRole('button', { name: 'เสนอเลขาธิการฯ ลงนาม คบ.9' })).toHaveCount(0)
  await handoffAction(page, 'accept', 'รับงานพร้อมเอกสารประกอบในแฟ้มเดิม')
  await expect.poll(async () => (await readHandoff(page))?.step).toBe('accepted')
  expect((await readCase(page, NO))?.documents).toEqual(baseDocs)
  expect((await readCase(page, NO))?.assignedOfficerUserId).toBe(originalOwner)
  await page.reload()
  await expect(page.getByTestId('handoff-status')).toContainText('รับงานแล้ว')

  // คบ.9 ลงนามพร้อมผลแล้ว: ผู้รับงานเติมรายละเอียด → ตรวจพร้อมส่ง → คบ.11 → วิธีที่ 1
  await completeNoticeDetails(page)
  await checkNoticeReady(page)
  const dispatch = page.getByText('การนำส่งหนังสือและวันที่พยานได้รับ').locator('xpath=ancestor::div[contains(@class,"rounded-xl")][1]')
  await dispatch.getByRole('button', { name: 'บันทึกการนำส่ง' }).click()
  await fieldAfterLabel(dispatch, 'ผู้รับหนังสือ').fill('นางสาวกมลชนก บุญรักษา')
  await dispatch.locator('input[type="file"]').setInputFiles({ name: 'ใบตอบรับสาธิต.pdf', mimeType: 'application/pdf', buffer: Buffer.from('demo delivery receipt') })
  await dispatch.getByRole('button', { name: 'ยืนยันการรับหนังสือ' }).click()
  await page.goto(`/form/11?caseNo=${NO}`)
  await page.getByTestId('kb11-form-sign').click()
  for (let i = 0; i < 4; i++) {
    await page.getByRole('button', { name: 'ลงลายมือชื่อ' }).first().click()
    await signInModal(page, i === 3 ? 'นางสาวณิชา คุ้มภัย' : 'ผู้ลงนามสาธิต')
  }
  await page.getByRole('button', { name: 'บันทึกข้อตกลง คบ.11' }).click()
  await expect.poll(async () => (await readCase(page, NO))?.kb11Signed).toBe(true)
  await page.goto(DOSSIER)
  await formRow(page, 'คบ.8').getByRole('button', { name: 'ส่งเสนอเลขาธิการฯ ลงนาม' }).click()
  await selectRole(page, 'secretary')
  await formRow(page, 'คบ.8').getByRole('button', { name: 'ลงนาม' }).click()
  await page.getByRole('button', { name: 'ลงนาม คบ.8' }).click()
  await signInModal(page)
  await page.getByRole('dialog', { name: /^ลงนาม คบ.8 -/ }).getByRole('button', { name: 'ปิด', exact: true }).click()
  await selectRole(page, 'got_officer')
  await page.goto(`/protection-method/1?caseNo=${NO}`)
  await page.getByLabel('สมาชิกชุดปฏิบัติและการจัดเวร').fill('ชุดคุ้มครองสาธิต กอท. แบ่งเวร 3 ผลัด')
  await page.getByLabel('ยานพาหนะ').fill('รถยนต์สาธิต 1 คัน')
  await page.getByRole('button', { name: 'ถัดไป' }).click()
  await page.getByLabel('ผู้ชี้แจง').fill('นางสาวณิชา คุ้มภัย')
  await page.getByTestId('method-1-start').click()
  await confirmDialog(page, 'ยืนยันเริ่มปฏิบัติจริง')
  await expect.poll(async () => (await readHandoff(page))?.step).toBe('active')
  const final = await readCase(page, NO)
  expect(final?.activity7State).toBe('approved')
  expect(final?.decisionNumber).toBe(orderNo)
  expect(final?.stage).toBe('protection')
  expect(final?.owner).toBe('นางสาวณิชา คุ้มภัย')
  const dispatchLog = (final?.assignmentHistory as any[]).find((e) => e.action.startsWith('บันทึกการนำส่งหนังสือแจ้งผล'))
  const receiptLog = (final?.assignmentHistory as any[]).find((e) => e.action === 'บันทึกวันที่พยานได้รับหนังสือ')
  expect(dispatchLog?.actor).toBe('นางสาวณิชา คุ้มภัย')
  expect(receiptLog?.actor).toBe('นางสาวณิชา คุ้มภัย')
  expect((final?.documents as any[]).filter((d) => d.id.startsWith('DOC-FINAL-'))).toHaveLength(1)
  expect((await readHandoff(page))?.events.map((e: any) => e.actorRole)).toEqual(['secretary', 'got_receiver', 'got_receiver', 'got_director', 'got_officer', 'got_officer'])
  await page.reload()
  expect((await readCase(page, NO))?.stage).toBe('protection')
  await selectRole(page, 'officer')
  await page.goto('/queue/officer')
  await expect(page.getByRole('row', { name: new RegExp(NO) })).toHaveCount(0)
})

test('ธุรการมอบหมายแทน ผอ. ไม่ได้ ส่งซ้ำไม่สร้างงาน/เอกสาร/ประวัติซ้ำ', async ({ page }) => {
  await seedMockState(page, 'PostApproval 3')
  await page.goto(DOSSIER)
  const results = await page.evaluate(async () => {
    const modulePath = '/scripts/post-approval-fixture.ts'
    const { useCaseStore } = await import(modulePath)
    const s = useCaseStore.getState()
    return [s.advanceProtectionHandoff('WP-2569-000501', 'assign', 'ข้ามขั้น', 'GOT-OFF-001'),
      s.advanceProtectionHandoff('WP-2569-000501', 'submit', 'ข้ามรับเรื่อง')]
  })
  expect(results).toEqual([false, false])
  await handoffAction(page, 'receive')
  const duplicate = await page.evaluate(async () => {
    const modulePath = '/scripts/post-approval-fixture.ts'
    const { useCaseStore } = await import(modulePath)
    return useCaseStore.getState().advanceProtectionHandoff('WP-2569-000501', 'receive', 'กดซ้ำ')
  })
  expect(duplicate).toBe(false)
  expect((await readHandoff(page))?.events).toHaveLength(2)
  expect((await readCase(page, NO))?.documents).toHaveLength(2)
  await page.reload()
  expect((await readHandoff(page))?.step).toBe('received')
})

test('ผู้ปฏิบัติงานที่ไม่ได้รับมอบหมายเปิดคิว/แฟ้ม/เอกสารของผู้อื่นไม่ได้', async ({ page }) => {
  await seedMockState(page, 'PostApproval 5')
  await page.goto('/queue/got_officer')
  await expect(page.getByRole('row', { name: new RegExp(NO) })).toBeVisible()
  await page.getByLabel('เลือกบัญชีเจ้าหน้าที่จำลอง').selectOption('GOT-OFF-002')
  await expect(page.getByRole('row', { name: new RegExp(NO) })).toHaveCount(0)
  await page.goto(DOSSIER)
  await expect(page.getByText('ไม่มีสิทธิ์เปิดแฟ้มนี้ในบทบาทปัจจุบัน')).toBeVisible()
  await page.goto(`/form/6?caseNo=${NO}`)
  await expect(page.getByText('ไม่มีสิทธิ์เปิดเอกสารของแฟ้มนี้ในบทบาทปัจจุบัน')).toBeVisible()
  await page.goto(`/protection-method/1?caseNo=${NO}`)
  await expect(page.getByText('ไม่มีสิทธิ์เปิดข้อมูลของแฟ้มนี้ในบทบาทปัจจุบัน')).toBeVisible()
})

for (const [name, role, step] of [
  ['PostApproval 2', 'officer', 'accepted'], ['PostApproval 3', 'got_receiver', 'pending_receipt'],
  ['PostApproval 4', 'got_director', 'pending_assignment'], ['PostApproval 5', 'got_officer', 'assigned'],
] as const) {
  test(`ข้อมูลสาธิต ${name} เปิดคิวพร้อมเดินต่อและรีเฟรชได้`, async ({ page }) => {
    await seedMockState(page, name)
    await page.goto(`/queue/${role}`)
    const row = page.getByRole('row', { name: new RegExp(NO) })
    await expect(row).toContainText('ข้อมูลสำหรับสาธิต')
    await row.getByRole('link', { name: 'เปิดแฟ้ม' }).click()
    await expect(page.getByTestId('protection-handoff-card')).toContainText('ข้อมูลสำหรับสาธิต')
    await expect(page.getByTestId('protection-handoff-card')).toContainText('30 วัน')
    await page.reload()
    expect((await readHandoff(page))?.step).toBe(step)
    expect((await readCase(page, NO))?.mainCaseNo).toBe('กบค. 001/2569')
    if (role === 'got_director') await expect(page.getByTestId('got-assignee-select')).toBeVisible()
    if (role === 'got_receiver') await expect(page.getByTestId('got-receive-button')).toBeVisible()
    if (role === 'got_officer') await expect(page.getByTestId('got-accept-button')).toBeVisible()
  })
}

test('หน้ามอบหมาย กอท. ใช้ได้ที่ 1440 / 1024 / 768 / 390 และผัง 07G แสดงครบ', async ({ page }, testInfo) => {
  await seedMockState(page, 'PostApproval 4')
  for (const width of [1440, 1024, 768, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto(DOSSIER)
    const card = page.getByTestId('protection-handoff-card')
    await expect(card).toBeVisible()
    await expect(page.getByTestId('got-assignee-select')).toBeVisible()
    await expect(page.getByTestId('got-assign-button')).toBeVisible()
    const box = await card.boundingBox()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(width + 1)
    const controlsOverflow = await card.evaluate((el) => el.scrollWidth > el.clientWidth + 1)
    expect(controlsOverflow).toBe(false)
    await card.screenshot({ path: testInfo.outputPath(`got-assignment-${width}.png`) })
    await page.screenshot({ path: testInfo.outputPath(`dossier-${width}.png`), fullPage: true })
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/flow-chart?tab=07G')
  await expect(page.getByRole('button', { name: /A6POST04/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /A6POST05/ })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('flow-07G.png'), fullPage: true })
})
