import { addProtectionMonths } from '../../src/lib/protectionMonths'
import { expect, test } from '@playwright/test'
import { seedMockState, readCase, switchRole } from '../helpers/seed'
const NO = 'WP-2569-009901'

test('แจ้งเตือนผู้รับผิดชอบปัจจุบันและเปิดงานทบทวนจากปุ่มข้าง คบ.13', async ({ page }) => {
  await seedMockState(page, 'Approved - วิธีที่ 4', undefined, { stage: 'method_operation' })
  await page.goto('/protection')
  await page.getByRole('button', { name: 'เพิ่มเคสตัวอย่างทบทวน / ขยายเวลา / ส่งต่อ', exact: true }).click()
  for (const cell of await page.locator('tbody tr td:last-child').all()) {
    await expect(cell.getByRole('link')).toHaveCount(1)
    await expect(cell.getByRole('link')).toHaveText('ดูระยะเวลาคุ้มครอง')
  }
  await page.screenshot({ path: '/private/tmp/a6-overview-single-action.png' })
  await page.goto('/protection-duration?caseNo=WP-2569-009902')
  await expect(page.getByRole('link', { name: 'ขอขยายเวลา คบ.14', exact: true })).toHaveAttribute('href', '/form/14?caseNo=WP-2569-009902')
  await page.goto('/protection-duration?caseNo=WP-2569-009903')
  await expect(page.getByRole('link', { name: 'ส่งต่อกรมคุ้มครองสิทธิฯ', exact: true })).toHaveAttribute('href', '/article14?caseNo=WP-2569-009903')
  await expect(page.getByRole('dialog', { name: 'แจ้งเตือนทบทวนการคุ้มครอง', exact: true })).not.toBeVisible()
  const original = await readCase(page, NO)
  await page.goto(`/protection-duration?caseNo=${NO}`)
  const dialog = page.getByRole('dialog', { name: 'แจ้งเตือนทบทวนการคุ้มครอง', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText(NO)
  await page.screenshot({ path: '/private/tmp/a6-review-reminder-verified.png' })
  await dialog.getByRole('button', { name: 'ภายหลัง', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  expect(await readCase(page, NO)).toEqual(original)
  await page.getByRole('link', { name: 'ขอขยายเวลา คบ.14', exact: true }).click()
  await expect(page).toHaveURL(`/form/14?caseNo=${NO}`)
  await expect(page.getByRole('textbox', { name: /เหตุผลความจำเป็น/ })).toHaveValue(/ภัยคุกคาม/)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '/private/tmp/a6-kb14-form.png', fullPage: true })
  await page.getByRole('button', { name: /ส่งให้ผู้บังคับบัญชาชั้นต้น/ }).click()
  await expect.poll(async () => (await readCase(page, NO)).extensionRequests?.at(-1)?.status).toBe('submitted')
  const submitted = await readCase(page, NO)
  expect(submitted.protectionEndAt).toBe(original.protectionEndAt)
  expect(submitted.reviewProposals).toEqual(original.reviewProposals)
  expect(submitted.extensionRequests.at(-1).durationMonths).toBe(1)
  await expect(page.getByText('ขอขยาย 1 เดือน', { exact: false })).toBeVisible()
  expect(submitted.extensionRequests.at(-1).formSnapshot['เหตุผลขยายเวลา']).toContain('ภัยคุกคาม')
  await switchRole(page, 'supervisor')
  await page.getByPlaceholder('ความเห็น / เหตุผลที่ส่งคืนแก้ไข').fill('ระบุเหตุผลเพิ่มเติม')
  await page.getByRole('button', { name: 'ส่งคืนแก้ไข', exact: true }).click()
  await page.getByRole('button', { name: 'ยืนยันส่งคืน', exact: true }).click()
  await expect.poll(async () => (await readCase(page, NO)).extensionRequests.at(-1).status).toBe('returned')
  await switchRole(page, 'officer')
  await page.getByRole('link', { name: 'เปิดแบบฟอร์ม คบ.14', exact: true }).click()
  await page.getByRole('button', { name: /ส่งให้ผู้บังคับบัญชาชั้นต้น/ }).click()
  await expect.poll(async () => (await readCase(page, NO)).extensionRequests.at(-1).version).toBe(2)
  expect((await readCase(page, NO)).extensionRequests.at(-1).previousVersions[0].formSnapshot).toEqual(submitted.extensionRequests.at(-1).formSnapshot)
  for (const [role, next, label] of [['supervisor', 'director', 'ผอ.กอง'], ['director', 'deputy_secretary', 'รองเลขาธิการ'], ['deputy_secretary', 'secretary', 'เลขาธิการ']]) {
    await switchRole(page, role)
    await expect(page.getByRole('button', { name: /อนุมัติขยายเวลา$/ })).toHaveCount(0)
    await page.getByRole('button', { name: `เห็นชอบ · ส่ง${label}`, exact: true }).click()
    await page.getByRole('button', { name: 'ยืนยันครบถ้วน', exact: true }).click()
    await expect.poll(async () => (await readCase(page, NO)).extensionRequests.at(-1).approvalStage).toBe(next)
    expect((await readCase(page, NO)).protectionEndAt).toBe(original.protectionEndAt)
  }
  await switchRole(page, 'secretary')
  await page.getByRole('button', { name: /อนุมัติขยายเวลา$/ }).click()
  await page.getByRole('button', { name: 'ยืนยันอนุมัติ', exact: true }).click()
  await expect.poll(async () => (await readCase(page, NO)).extensionRequests.at(-1).status).toBe('approved')
  expect((await readCase(page, NO)).owner).toBe(original.assignedOfficer)
  expect((await readCase(page, NO)).protectionEndAt).toBe(addProtectionMonths(original.protectionEndAt, 1))
})

test('ผู้กลั่นกรองไม่รับ popup แจ้งเตือนแทนผู้รับผิดชอบ', async ({ page }) => {
  await seedMockState(page, 'Approved - วิธีที่ 4', 'secretary', { stage: 'method_operation' })
  await page.goto('/protection')
  await page.getByRole('button', { name: 'เพิ่มเคสตัวอย่างทบทวน / ขยายเวลา / ส่งต่อ', exact: true }).click()
  await page.goto(`/protection-duration?caseNo=${NO}`)
  await expect(page.getByRole('dialog', { name: 'แจ้งเตือนทบทวนการคุ้มครอง', exact: true })).not.toBeVisible()
  await expect(page.getByRole('link', { name: 'ขอขยายเวลา คบ.14', exact: true })).toHaveCount(0)
})
