import { expect, test } from '@playwright/test'
import { readCase, seedMockState } from '../helpers/seed'

const NO = 'WP-2569-000501'
test('เลือกที่มาของเรื่องยุติได้ชัดเจน บันทึกแล้วจัดทำ คบ.15 โดยยังไม่ยุติการคุ้มครอง', async ({ page }) => {
  await seedMockState(page, 'Approved - วิธีที่ 4', undefined, { stage: 'protection', terminationTrigger: undefined, kb15: undefined, kb16: undefined, kb17: undefined })
  await page.goto(`/termination/${NO}`)
  const form = page.getByTestId('termination-trigger-form')
  await expect(form.getByRole('radio')).toHaveCount(3)
  await form.getByRole('radio', { name: /พยานขอยุติ/ }).click()
  await expect(page).toHaveURL(new RegExp(`/form/7\\?caseNo=${NO}&from=termination`))
  await page.locator('textarea[placeholder="ระบุเหตุผลและผลการประเมินความปลอดภัยล่าสุด..."]').fill('พยานประสงค์ขอยุติ')
  await page.getByRole('button', { name: /บันทึก คบ.7 และกลับเรื่องยุติ/ }).click()
  await expect(page).toHaveURL(new RegExp(`/termination/${NO}`))
  await expect(form.getByRole('radio', { name: /พยานขอยุติ/ })).toBeChecked()
  await expect(form.getByRole('textbox', { name: 'เหตุผลและข้อมูลประกอบ', exact: true })).toHaveValue('พยานประสงค์ขอยุติ')
  expect((await readCase(page, NO)).stage).toBe('protection')
  expect((await readCase(page, NO)).terminationTrigger).toBeUndefined()
  await expect(form.getByRole('button', { name: 'เปิดแบบ คบ.7', exact: true })).toBeVisible()
  await expect(form.getByRole('textbox', { name: 'ไฟล์ คบ.7 ที่พยานลงนาม *', exact: true })).toBeVisible()
  await page.evaluate(() => {
    const key = 'ecmis-case-storage-v2'
    const store = JSON.parse(localStorage.getItem(key)!)
    store.state.cases.push({ ...store.state.cases[0], no: 'WP-2569-000999', person: 'พยานอื่น ทดสอบ' })
    localStorage.setItem(key, JSON.stringify(store))
  })
  await page.goto('/form/7?caseNo=WP-2569-000999&from=termination')
  await expect(page.locator('textarea[placeholder="ระบุเหตุผลและผลการประเมินความปลอดภัยล่าสุด..."]')).toHaveValue('')
  await page.goto(`/form/7?caseNo=${NO}&from=termination`)
  await expect(page.locator('textarea[placeholder="ระบุเหตุผลและผลการประเมินความปลอดภัยล่าสุด..."]')).toHaveValue('พยานประสงค์ขอยุติ')
  await page.getByRole('link', { name: /กลับเรื่องยุติการคุ้มครอง/ }).click()
  await form.getByRole('radio', { name: /หนังสือภายนอก/ }).check()
  await expect(form.getByRole('textbox', { name: 'หน่วยงานผู้ส่งหนังสือ', exact: true })).toBeVisible()
  await form.getByRole('radio', { name: /เจ้าหน้าที่เสนอ/ }).check()
  for (const width of [1440, 1024, 768, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await form.screenshot({ path: '/private/tmp/a6-termination-intake.png' })
  await form.getByRole('textbox', { name: 'คำสั่งที่ครบกำหนด *', exact: true }).fill('ลธ. 501/2569')
  await form.getByRole('textbox', { name: 'เหตุผลและข้อมูลประกอบ', exact: true }).fill('ผลประเมินล่าสุดไม่พบภัย ขอเสนอให้พิจารณายุติ')
  await form.getByRole('button', { name: 'บันทึกเรื่องยุติ', exact: true }).click()
  await expect.poll(async () => (await readCase(page, NO)).terminationTrigger?.ref).toBe('ลธ. 501/2569')
  expect((await readCase(page, NO)).stage).toBe('termination_review')
  expect((await readCase(page, NO)).kb15).toBeUndefined()
  await page.reload()
  await expect(page.getByText('เพิ่มเหตุยุติที่เกิดพร้อมกัน (ถ้ามี)', { exact: true })).toHaveCount(0)
  await expect(page.getByText('เหตุเริ่มยุติ:', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'จัดทำ คบ.15', exact: true })).toBeVisible()
})
