/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Activity7ResultsRouteImport } from './routes/activity7-results'
import { Route as AppealRouteImport } from './routes/appeal'
import { Route as Article14RouteImport } from './routes/article14'
import { Route as DeliveryTrackingRouteImport } from './routes/delivery-tracking'
import { Route as FlowChartRouteImport } from './routes/flow-chart'
import { Route as FlowGuideRouteImport } from './routes/flow-guide'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as MockStateRouteImport } from './routes/mock-state'
import { Route as NoticeRouteImport } from './routes/notice'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProtectionRouteImport } from './routes/protection'
import { Route as ProtectionDurationRouteImport } from './routes/protection-duration'
import { Route as ProtectionExtensionsRouteImport } from './routes/protection-extensions'
import { Route as ProtectionMethodWorkRouteImport } from './routes/protection-method-work'
import { Route as ProtectionMethodsRouteImport } from './routes/protection-methods'
import { Route as ProtectionMonitorRouteImport } from './routes/protection-monitor'
import { Route as ProtectionReviewsRouteImport } from './routes/protection-reviews'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TerminationRouteImport } from './routes/termination'
import { Route as AppealFolderCaseNoRouteImport } from './routes/appeal-folder/$caseNo'
import { Route as DossierCaseNoRouteImport } from './routes/dossier/$caseNo'
import { Route as FormFormIdRouteImport } from './routes/form/$formId'
import { Route as ProtectionExtensionCaseNoRouteImport } from './routes/protection-extension/$caseNo'
import { Route as ProtectionMethodMethodRouteImport } from './routes/protection-method/$method'
import { Route as ProtectionReviewCaseNoRouteImport } from './routes/protection-review/$caseNo'
import { Route as QueueRoleRouteImport } from './routes/queue/$role'
import { Route as SignTokenRouteImport } from './routes/sign/$token'
import { Route as TerminationCaseNoRouteImport } from './routes/termination/$caseNo'
import { Route as SignConsentTokenRouteImport } from './routes/sign/consent/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Activity7ResultsRoute = Activity7ResultsRouteImport.update({
  id: '/activity7-results',
  path: '/activity7-results',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealRoute = AppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const Article14Route = Article14RouteImport.update({
  id: '/article14',
  path: '/article14',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryTrackingRoute = DeliveryTrackingRouteImport.update({
  id: '/delivery-tracking',
  path: '/delivery-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowChartRoute = FlowChartRouteImport.update({
  id: '/flow-chart',
  path: '/flow-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowGuideRoute = FlowGuideRouteImport.update({
  id: '/flow-guide',
  path: '/flow-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const MockStateRoute = MockStateRouteImport.update({
  id: '/mock-state',
  path: '/mock-state',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeRoute = NoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionRoute = ProtectionRouteImport.update({
  id: '/protection',
  path: '/protection',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionDurationRoute = ProtectionDurationRouteImport.update({
  id: '/protection-duration',
  path: '/protection-duration',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionExtensionsRoute = ProtectionExtensionsRouteImport.update({
  id: '/protection-extensions',
  path: '/protection-extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionMethodWorkRoute = ProtectionMethodWorkRouteImport.update({
  id: '/protection-method-work',
  path: '/protection-method-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionMethodsRoute = ProtectionMethodsRouteImport.update({
  id: '/protection-methods',
  path: '/protection-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionMonitorRoute = ProtectionMonitorRouteImport.update({
  id: '/protection-monitor',
  path: '/protection-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionReviewsRoute = ProtectionReviewsRouteImport.update({
  id: '/protection-reviews',
  path: '/protection-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminationRoute = TerminationRouteImport.update({
  id: '/termination',
  path: '/termination',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealFolderCaseNoRoute = AppealFolderCaseNoRouteImport.update({
  id: '/appeal-folder/$caseNo',
  path: '/appeal-folder/$caseNo',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierCaseNoRoute = DossierCaseNoRouteImport.update({
  id: '/dossier/$caseNo',
  path: '/dossier/$caseNo',
  getParentRoute: () => rootRouteImport,
} as any)
const FormFormIdRoute = FormFormIdRouteImport.update({
  id: '/form/$formId',
  path: '/form/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionExtensionCaseNoRoute =
  ProtectionExtensionCaseNoRouteImport.update({
    id: '/protection-extension/$caseNo',
    path: '/protection-extension/$caseNo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectionMethodMethodRoute = ProtectionMethodMethodRouteImport.update({
  id: '/protection-method/$method',
  path: '/protection-method/$method',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionReviewCaseNoRoute = ProtectionReviewCaseNoRouteImport.update({
  id: '/protection-review/$caseNo',
  path: '/protection-review/$caseNo',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoleRoute = QueueRoleRouteImport.update({
  id: '/queue/$role',
  path: '/queue/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminationCaseNoRoute = TerminationCaseNoRouteImport.update({
  id: '/$caseNo',
  path: '/$caseNo',
  getParentRoute: () => TerminationRoute,
} as any)
const SignConsentTokenRoute = SignConsentTokenRouteImport.update({
  id: '/sign/consent/$token',
  path: '/sign/consent/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity7-results': typeof Activity7ResultsRoute
  '/appeal': typeof AppealRoute
  '/article14': typeof Article14Route
  '/delivery-tracking': typeof DeliveryTrackingRoute
  '/flow-chart': typeof FlowChartRoute
  '/flow-guide': typeof FlowGuideRoute
  '/forms': typeof FormsRoute
  '/intake': typeof IntakeRoute
  '/mock-state': typeof MockStateRoute
  '/notice': typeof NoticeRoute
  '/notifications': typeof NotificationsRoute
  '/protection': typeof ProtectionRoute
  '/protection-duration': typeof ProtectionDurationRoute
  '/protection-extensions': typeof ProtectionExtensionsRoute
  '/protection-method-work': typeof ProtectionMethodWorkRoute
  '/protection-methods': typeof ProtectionMethodsRoute
  '/protection-monitor': typeof ProtectionMonitorRoute
  '/protection-reviews': typeof ProtectionReviewsRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/termination': typeof TerminationRouteWithChildren
  '/appeal-folder/$caseNo': typeof AppealFolderCaseNoRoute
  '/dossier/$caseNo': typeof DossierCaseNoRoute
  '/form/$formId': typeof FormFormIdRoute
  '/protection-extension/$caseNo': typeof ProtectionExtensionCaseNoRoute
  '/protection-method/$method': typeof ProtectionMethodMethodRoute
  '/protection-review/$caseNo': typeof ProtectionReviewCaseNoRoute
  '/queue/$role': typeof QueueRoleRoute
  '/sign/$token': typeof SignTokenRoute
  '/termination/$caseNo': typeof TerminationCaseNoRoute
  '/sign/consent/$token': typeof SignConsentTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity7-results': typeof Activity7ResultsRoute
  '/appeal': typeof AppealRoute
  '/article14': typeof Article14Route
  '/delivery-tracking': typeof DeliveryTrackingRoute
  '/flow-chart': typeof FlowChartRoute
  '/flow-guide': typeof FlowGuideRoute
  '/forms': typeof FormsRoute
  '/intake': typeof IntakeRoute
  '/mock-state': typeof MockStateRoute
  '/notice': typeof NoticeRoute
  '/notifications': typeof NotificationsRoute
  '/protection': typeof ProtectionRoute
  '/protection-duration': typeof ProtectionDurationRoute
  '/protection-extensions': typeof ProtectionExtensionsRoute
  '/protection-method-work': typeof ProtectionMethodWorkRoute
  '/protection-methods': typeof ProtectionMethodsRoute
  '/protection-monitor': typeof ProtectionMonitorRoute
  '/protection-reviews': typeof ProtectionReviewsRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/termination': typeof TerminationRouteWithChildren
  '/appeal-folder/$caseNo': typeof AppealFolderCaseNoRoute
  '/dossier/$caseNo': typeof DossierCaseNoRoute
  '/form/$formId': typeof FormFormIdRoute
  '/protection-extension/$caseNo': typeof ProtectionExtensionCaseNoRoute
  '/protection-method/$method': typeof ProtectionMethodMethodRoute
  '/protection-review/$caseNo': typeof ProtectionReviewCaseNoRoute
  '/queue/$role': typeof QueueRoleRoute
  '/sign/$token': typeof SignTokenRoute
  '/termination/$caseNo': typeof TerminationCaseNoRoute
  '/sign/consent/$token': typeof SignConsentTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity7-results': typeof Activity7ResultsRoute
  '/appeal': typeof AppealRoute
  '/article14': typeof Article14Route
  '/delivery-tracking': typeof DeliveryTrackingRoute
  '/flow-chart': typeof FlowChartRoute
  '/flow-guide': typeof FlowGuideRoute
  '/forms': typeof FormsRoute
  '/intake': typeof IntakeRoute
  '/mock-state': typeof MockStateRoute
  '/notice': typeof NoticeRoute
  '/notifications': typeof NotificationsRoute
  '/protection': typeof ProtectionRoute
  '/protection-duration': typeof ProtectionDurationRoute
  '/protection-extensions': typeof ProtectionExtensionsRoute
  '/protection-method-work': typeof ProtectionMethodWorkRoute
  '/protection-methods': typeof ProtectionMethodsRoute
  '/protection-monitor': typeof ProtectionMonitorRoute
  '/protection-reviews': typeof ProtectionReviewsRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/termination': typeof TerminationRouteWithChildren
  '/appeal-folder/$caseNo': typeof AppealFolderCaseNoRoute
  '/dossier/$caseNo': typeof DossierCaseNoRoute
  '/form/$formId': typeof FormFormIdRoute
  '/protection-extension/$caseNo': typeof ProtectionExtensionCaseNoRoute
  '/protection-method/$method': typeof ProtectionMethodMethodRoute
  '/protection-review/$caseNo': typeof ProtectionReviewCaseNoRoute
  '/queue/$role': typeof QueueRoleRoute
  '/sign/$token': typeof SignTokenRoute
  '/termination/$caseNo': typeof TerminationCaseNoRoute
  '/sign/consent/$token': typeof SignConsentTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity7-results'
    | '/appeal'
    | '/article14'
    | '/delivery-tracking'
    | '/flow-chart'
    | '/flow-guide'
    | '/forms'
    | '/intake'
    | '/mock-state'
    | '/notice'
    | '/notifications'
    | '/protection'
    | '/protection-duration'
    | '/protection-extensions'
    | '/protection-method-work'
    | '/protection-methods'
    | '/protection-monitor'
    | '/protection-reviews'
    | '/registry'
    | '/reports'
    | '/termination'
    | '/appeal-folder/$caseNo'
    | '/dossier/$caseNo'
    | '/form/$formId'
    | '/protection-extension/$caseNo'
    | '/protection-method/$method'
    | '/protection-review/$caseNo'
    | '/queue/$role'
    | '/sign/$token'
    | '/termination/$caseNo'
    | '/sign/consent/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity7-results'
    | '/appeal'
    | '/article14'
    | '/delivery-tracking'
    | '/flow-chart'
    | '/flow-guide'
    | '/forms'
    | '/intake'
    | '/mock-state'
    | '/notice'
    | '/notifications'
    | '/protection'
    | '/protection-duration'
    | '/protection-extensions'
    | '/protection-method-work'
    | '/protection-methods'
    | '/protection-monitor'
    | '/protection-reviews'
    | '/registry'
    | '/reports'
    | '/termination'
    | '/appeal-folder/$caseNo'
    | '/dossier/$caseNo'
    | '/form/$formId'
    | '/protection-extension/$caseNo'
    | '/protection-method/$method'
    | '/protection-review/$caseNo'
    | '/queue/$role'
    | '/sign/$token'
    | '/termination/$caseNo'
    | '/sign/consent/$token'
  id:
    | '__root__'
    | '/'
    | '/activity7-results'
    | '/appeal'
    | '/article14'
    | '/delivery-tracking'
    | '/flow-chart'
    | '/flow-guide'
    | '/forms'
    | '/intake'
    | '/mock-state'
    | '/notice'
    | '/notifications'
    | '/protection'
    | '/protection-duration'
    | '/protection-extensions'
    | '/protection-method-work'
    | '/protection-methods'
    | '/protection-monitor'
    | '/protection-reviews'
    | '/registry'
    | '/reports'
    | '/termination'
    | '/appeal-folder/$caseNo'
    | '/dossier/$caseNo'
    | '/form/$formId'
    | '/protection-extension/$caseNo'
    | '/protection-method/$method'
    | '/protection-review/$caseNo'
    | '/queue/$role'
    | '/sign/$token'
    | '/termination/$caseNo'
    | '/sign/consent/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Activity7ResultsRoute: typeof Activity7ResultsRoute
  AppealRoute: typeof AppealRoute
  Article14Route: typeof Article14Route
  DeliveryTrackingRoute: typeof DeliveryTrackingRoute
  FlowChartRoute: typeof FlowChartRoute
  FlowGuideRoute: typeof FlowGuideRoute
  FormsRoute: typeof FormsRoute
  IntakeRoute: typeof IntakeRoute
  MockStateRoute: typeof MockStateRoute
  NoticeRoute: typeof NoticeRoute
  NotificationsRoute: typeof NotificationsRoute
  ProtectionRoute: typeof ProtectionRoute
  ProtectionDurationRoute: typeof ProtectionDurationRoute
  ProtectionExtensionsRoute: typeof ProtectionExtensionsRoute
  ProtectionMethodWorkRoute: typeof ProtectionMethodWorkRoute
  ProtectionMethodsRoute: typeof ProtectionMethodsRoute
  ProtectionMonitorRoute: typeof ProtectionMonitorRoute
  ProtectionReviewsRoute: typeof ProtectionReviewsRoute
  RegistryRoute: typeof RegistryRoute
  ReportsRoute: typeof ReportsRoute
  TerminationRoute: typeof TerminationRouteWithChildren
  AppealFolderCaseNoRoute: typeof AppealFolderCaseNoRoute
  DossierCaseNoRoute: typeof DossierCaseNoRoute
  FormFormIdRoute: typeof FormFormIdRoute
  ProtectionExtensionCaseNoRoute: typeof ProtectionExtensionCaseNoRoute
  ProtectionMethodMethodRoute: typeof ProtectionMethodMethodRoute
  ProtectionReviewCaseNoRoute: typeof ProtectionReviewCaseNoRoute
  QueueRoleRoute: typeof QueueRoleRoute
  SignTokenRoute: typeof SignTokenRoute
  SignConsentTokenRoute: typeof SignConsentTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity7-results': {
      id: '/activity7-results'
      path: '/activity7-results'
      fullPath: '/activity7-results'
      preLoaderRoute: typeof Activity7ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal': {
      id: '/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article14': {
      id: '/article14'
      path: '/article14'
      fullPath: '/article14'
      preLoaderRoute: typeof Article14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-tracking': {
      id: '/delivery-tracking'
      path: '/delivery-tracking'
      fullPath: '/delivery-tracking'
      preLoaderRoute: typeof DeliveryTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-chart': {
      id: '/flow-chart'
      path: '/flow-chart'
      fullPath: '/flow-chart'
      preLoaderRoute: typeof FlowChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-guide': {
      id: '/flow-guide'
      path: '/flow-guide'
      fullPath: '/flow-guide'
      preLoaderRoute: typeof FlowGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-state': {
      id: '/mock-state'
      path: '/mock-state'
      fullPath: '/mock-state'
      preLoaderRoute: typeof MockStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice': {
      id: '/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection': {
      id: '/protection'
      path: '/protection'
      fullPath: '/protection'
      preLoaderRoute: typeof ProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-duration': {
      id: '/protection-duration'
      path: '/protection-duration'
      fullPath: '/protection-duration'
      preLoaderRoute: typeof ProtectionDurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-extensions': {
      id: '/protection-extensions'
      path: '/protection-extensions'
      fullPath: '/protection-extensions'
      preLoaderRoute: typeof ProtectionExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-method-work': {
      id: '/protection-method-work'
      path: '/protection-method-work'
      fullPath: '/protection-method-work'
      preLoaderRoute: typeof ProtectionMethodWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-methods': {
      id: '/protection-methods'
      path: '/protection-methods'
      fullPath: '/protection-methods'
      preLoaderRoute: typeof ProtectionMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-monitor': {
      id: '/protection-monitor'
      path: '/protection-monitor'
      fullPath: '/protection-monitor'
      preLoaderRoute: typeof ProtectionMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-reviews': {
      id: '/protection-reviews'
      path: '/protection-reviews'
      fullPath: '/protection-reviews'
      preLoaderRoute: typeof ProtectionReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termination': {
      id: '/termination'
      path: '/termination'
      fullPath: '/termination'
      preLoaderRoute: typeof TerminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal-folder/$caseNo': {
      id: '/appeal-folder/$caseNo'
      path: '/appeal-folder/$caseNo'
      fullPath: '/appeal-folder/$caseNo'
      preLoaderRoute: typeof AppealFolderCaseNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/$caseNo': {
      id: '/dossier/$caseNo'
      path: '/dossier/$caseNo'
      fullPath: '/dossier/$caseNo'
      preLoaderRoute: typeof DossierCaseNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$formId': {
      id: '/form/$formId'
      path: '/form/$formId'
      fullPath: '/form/$formId'
      preLoaderRoute: typeof FormFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-extension/$caseNo': {
      id: '/protection-extension/$caseNo'
      path: '/protection-extension/$caseNo'
      fullPath: '/protection-extension/$caseNo'
      preLoaderRoute: typeof ProtectionExtensionCaseNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-method/$method': {
      id: '/protection-method/$method'
      path: '/protection-method/$method'
      fullPath: '/protection-method/$method'
      preLoaderRoute: typeof ProtectionMethodMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-review/$caseNo': {
      id: '/protection-review/$caseNo'
      path: '/protection-review/$caseNo'
      fullPath: '/protection-review/$caseNo'
      preLoaderRoute: typeof ProtectionReviewCaseNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$role': {
      id: '/queue/$role'
      path: '/queue/$role'
      fullPath: '/queue/$role'
      preLoaderRoute: typeof QueueRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termination/$caseNo': {
      id: '/termination/$caseNo'
      path: '/$caseNo'
      fullPath: '/termination/$caseNo'
      preLoaderRoute: typeof TerminationCaseNoRouteImport
      parentRoute: typeof TerminationRoute
    }
    '/sign/consent/$token': {
      id: '/sign/consent/$token'
      path: '/sign/consent/$token'
      fullPath: '/sign/consent/$token'
      preLoaderRoute: typeof SignConsentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TerminationRouteChildren {
  TerminationCaseNoRoute: typeof TerminationCaseNoRoute
}

const TerminationRouteChildren: TerminationRouteChildren = {
  TerminationCaseNoRoute: TerminationCaseNoRoute,
}

const TerminationRouteWithChildren = TerminationRoute._addFileChildren(
  TerminationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Activity7ResultsRoute: Activity7ResultsRoute,
  AppealRoute: AppealRoute,
  Article14Route: Article14Route,
  DeliveryTrackingRoute: DeliveryTrackingRoute,
  FlowChartRoute: FlowChartRoute,
  FlowGuideRoute: FlowGuideRoute,
  FormsRoute: FormsRoute,
  IntakeRoute: IntakeRoute,
  MockStateRoute: MockStateRoute,
  NoticeRoute: NoticeRoute,
  NotificationsRoute: NotificationsRoute,
  ProtectionRoute: ProtectionRoute,
  ProtectionDurationRoute: ProtectionDurationRoute,
  ProtectionExtensionsRoute: ProtectionExtensionsRoute,
  ProtectionMethodWorkRoute: ProtectionMethodWorkRoute,
  ProtectionMethodsRoute: ProtectionMethodsRoute,
  ProtectionMonitorRoute: ProtectionMonitorRoute,
  ProtectionReviewsRoute: ProtectionReviewsRoute,
  RegistryRoute: RegistryRoute,
  ReportsRoute: ReportsRoute,
  TerminationRoute: TerminationRouteWithChildren,
  AppealFolderCaseNoRoute: AppealFolderCaseNoRoute,
  DossierCaseNoRoute: DossierCaseNoRoute,
  FormFormIdRoute: FormFormIdRoute,
  ProtectionExtensionCaseNoRoute: ProtectionExtensionCaseNoRoute,
  ProtectionMethodMethodRoute: ProtectionMethodMethodRoute,
  ProtectionReviewCaseNoRoute: ProtectionReviewCaseNoRoute,
  QueueRoleRoute: QueueRoleRoute,
  SignTokenRoute: SignTokenRoute,
  SignConsentTokenRoute: SignConsentTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
